const people={Will:{initials:'WK',avatar:'avatar-will'},Jillian:{initials:'JD',avatar:'avatar-jillian'},Karen:{initials:'KD',avatar:'avatar-karen'}};
const data=[
{id:'1',type:'food',mine:true,saved:false,author:'Will',date:'2026-07-12',name:'Crispy Salmon Rice Bowls',rating:8.4,img:'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1400&q=85',tags:['Dinner','Asian','35 min'],best:['Quick Weeknight','Date Night','Healthy'],method:'Stovetop',cuisine:'Asian',occasion:'Dinner',dishType:'Dinner',source:'Defined Dish',url:'https://thedefineddish.com',likes:14,comments:4,review:'The salmon got beautifully crisp and the spicy mayo tied everything together. Next time I’d double the cucumber salad and use a little less rice.',changes:'Added extra lime and jalapeño.',next:'Double the cucumber salad.',ingredients:['1 lb salmon, cubed','2 cups cooked rice','1 cucumber, thinly sliced','2 tbsp soy sauce','Spicy mayo, to taste'],directions:['Season and sear the salmon until deeply golden.','Toss cucumber with lime and salt.','Build bowls with rice, salmon, cucumber, and spicy mayo.'],history:[{date:'Jul 2026',rating:8.4,note:'Added extra lime. Great balance.'},{date:'May 2026',rating:7.8,note:'Needed more cucumber and sauce.'},{date:'Mar 2026',rating:7.1,note:'Good first try, but too much rice.'}]},
{id:'2',type:'cocktail',mine:false,saved:true,author:'Jillian',date:'2026-07-11',name:'Cucumber Tequila Cooler',rating:7.2,img:'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?auto=format&fit=crop&w=1400&q=85',tags:['Tequila','Easy','On the Rocks'],best:['Date Night'],baseSpirit:'Tequila',style:['On the Rocks','Shaken'],difficulty:'Easy',flavor:['Citrusy','Refreshing','Sour'],season:'Summer',source:'Cocktail Friday',url:'',likes:11,comments:2,review:'Exactly what you want before dinner on a hot night. Bright, cold, and not too sweet.',changes:'Added a pinch of salt.',next:'More lime, less cucumber.',ingredients:['2 oz blanco tequila','3 cucumber slices','¾ oz lime juice','½ oz simple syrup','Soda water'],directions:['Muddle cucumber lightly.','Shake tequila, lime, and syrup with ice.','Strain over fresh ice and top with soda.'],history:[{date:'Jul 2026',rating:7.2,note:'Refreshing. More lime next time.'}]},
{id:'3',type:'food',mine:false,saved:false,author:'Karen',date:'2026-07-09',name:'Charred Corn Fish Tacos',rating:7.8,img:'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?auto=format&fit=crop&w=1400&q=85',tags:['Dinner','Mexican','42 min'],best:['For a Party','Family Dinner'],method:'Grill',cuisine:'Mexican',occasion:'Dinner',dishType:'Dinner',source:'NYT Cooking',url:'https://cooking.nytimes.com',likes:18,comments:6,review:'Very good and easy to scale for a group. The charred corn salsa was the best part.',changes:'Added avocado.',next:'Season the fish more aggressively.',ingredients:['1½ lb white fish','8 corn tortillas','2 ears corn','1 avocado','Lime crema'],directions:['Grill the corn and fish.','Make salsa with corn, lime, and herbs.','Warm tortillas and assemble.'],history:[{date:'Jul 2026',rating:7.8,note:'Great for a group.'}]},
{id:'4',type:'food',mine:true,saved:false,author:'Will',date:'2026-07-04',name:'Sunday Red Sauce',rating:9.6,img:'https://images.unsplash.com/photo-1551892374-ecf8754cf8b0?auto=format&fit=crop&w=1400&q=85',tags:['Dinner','Italian','3 hr 30'],best:['Weekend Project','Great Leftovers','Treat Yourself'],method:'Stovetop',cuisine:'Italian',occasion:'Dinner',dishType:'Pasta',source:'Family Recipe',url:'',likes:23,comments:8,review:'An all-timer. Deep flavor, tender pork, and even better the next day.',changes:'Added a parmesan rind.',next:'Make a double batch.',ingredients:['2 cans whole tomatoes','1 lb pork shoulder','1 onion','6 garlic cloves','Parmesan rind'],directions:['Brown the pork deeply.','Build the sauce and add tomatoes.','Simmer low for three hours.'],history:[{date:'Jul 2026',rating:9.6,note:'Benchmark version.'},{date:'Jan 2026',rating:9.1,note:'Parmesan rind changed everything.'},{date:'Oct 2025',rating:8.7,note:'Needed more time on low heat.'}]},
{id:'5',type:'cocktail',mine:true,saved:false,author:'Will',date:'2026-06-29',name:'Paper Plane',rating:8.8,img:'https://images.unsplash.com/photo-1560512823-829485b8bf24?auto=format&fit=crop&w=1400&q=85',tags:['Bourbon','Bar Cart Required','Up'],best:['Date Night','Treat Yourself'],baseSpirit:'Bourbon',style:['Up','Shaken'],difficulty:'Bar Cart Required',flavor:['Bitter','Citrusy','Refreshing'],season:'Anytime',source:'Sam Ross',url:'https://www.google.com/search?q=paper+plane+cocktail',likes:9,comments:3,review:'Perfect balance and way more approachable than the ingredient list sounds.',changes:'None.',next:'Chill the glass longer.',ingredients:['¾ oz bourbon','¾ oz Aperol','¾ oz Amaro Nonino','¾ oz lemon juice'],directions:['Shake all ingredients with ice.','Double strain into a chilled coupe.'],history:[{date:'Jun 2026',rating:8.8,note:'Worth owning the bottles.'},{date:'Feb 2026',rating:8.4,note:'Needed a colder glass.'}]},
{id:'6',type:'food',mine:true,saved:false,author:'Will',date:'2026-06-25',name:'Sheet-Pan Chicken Shawarma',rating:5.3,img:'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=1400&q=85',tags:['Dinner','Mediterranean','50 min'],best:['Quick Weeknight','Meal Prep','Healthy'],method:'Oven',cuisine:'Mediterranean',occasion:'Dinner',dishType:'Dinner',source:'Defined Dish',url:'https://thedefineddish.com',likes:4,comments:1,review:'Perfectly fine but not memorable. The chicken dried out and the spice mix needed more punch.',changes:'Used chicken breasts.',next:'Use thighs and more seasoning.',ingredients:['2 lb chicken','1 red onion','Shawarma spice','Greek yogurt sauce'],directions:['Season chicken and onion.','Roast until browned.','Serve with yogurt sauce.'],history:[{date:'Jun 2026',rating:5.3,note:'Fine, but use thighs next time.'}]},
{id:'7',type:'food',mine:false,saved:true,author:'Karen',date:'2026-06-21',name:'Summer Peach Burrata',rating:9.1,img:'https://images.unsplash.com/photo-1625944525533-473f1a3d54e7?auto=format&fit=crop&w=1400&q=85',tags:['Appetizer','Italian','15 min'],best:['For a Party','Treat Yourself'],method:'No Cook',cuisine:'Italian',occasion:'Party',dishType:'Appetizer',source:'Half Baked Harvest',url:'https://www.halfbakedharvest.com',likes:31,comments:7,review:'Simple, seasonal, and much better than the effort required.',changes:'Added basil.',next:'Use even riper peaches.',ingredients:['3 peaches','8 oz burrata','Hot honey','Basil','Flaky salt'],directions:['Slice peaches.','Arrange with burrata.','Finish with hot honey, basil, and salt.'],history:[{date:'Jun 2026',rating:9.1,note:'Restaurant-worthy for almost no effort.'}]}
];
let quick='all',minRating=1,panelType='all',advanced={};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function fmt(d){return new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric'}).format(new Date(d+'T12:00:00'))}
function meaning(r){return r<2?'Disaster':r<3?'Would rather have Canned Tuna':r<4?'Might as well get Mickie Ds':r<5?'If I’m drunk, I’ll eat it':r<6?'Fine — would be okay to have again':r<7?'A good, solid meal':r<8?'I enjoyed that':r<9?'Things are heating up, I need more':r<10?'I can’t talk, gotta eat':'Cherish every bite'}
function person(e){const p=people[e.author];return `<span class="authorperson"><b class="avatar ${p.avatar}">${p.initials}</b><strong>${e.author}</strong></span>`}
function card(e,small=false){return `<article class="${small?'smallcard':'card'}" data-id="${e.id}"><div class="media"><img src="${e.img}" alt="${e.name}"><span class="badge">${e.type==='food'?'Food':'Cocktail'}</span><span class="score">${e.rating.toFixed(1)}</span></div><div class="body"><div class="author">${person(e)}<span class="date">${fmt(e.date)}</span></div><h3>${e.name}</h3><div class="pills">${e.tags.map(t=>`<span class="pill">${t}</span>`).join('')}</div><p class="review">${e.review}</p><div class="footer"><span>♡ ${e.likes} &nbsp; ◌ ${e.comments} &nbsp; ${e.saved?'★ Saved':'☆ Save'}</span><span class="recommend">${e.rating>=5?'✓ 5+':'Wouldn’t repeat'}</span></div></div></article>`}
function bind(){$$('[data-id]').forEach(x=>x.onclick=()=>openDetail(x.dataset.id))}
function matchesAdvanced(e){if(e.type==='food'){if(advanced.method&&e.method!==advanced.method)return false;if(advanced.cuisine&&e.cuisine!==advanced.cuisine)return false;if(advanced.occasion&&e.occasion!==advanced.occasion)return false;if(advanced.dishType&&e.dishType!==advanced.dishType)return false;if(advanced.bestFor&&!e.best.includes(advanced.bestFor))return false}else{if(advanced.baseSpirit&&e.baseSpirit!==advanced.baseSpirit)return false;if(advanced.style&&!e.style.includes(advanced.style))return false;if(advanced.difficulty&&e.difficulty!==advanced.difficulty)return false;if(advanced.flavor&&!e.flavor.includes(advanced.flavor))return false;if(advanced.season&&e.season!==advanced.season)return false}return true}
function renderFeed(){let arr=[...data];if(['food','cocktail'].includes(quick))arr=arr.filter(e=>e.type===quick);if(quick==='weeknight')arr=arr.filter(e=>e.best.includes('Quick Weeknight'));if(quick==='party')arr=arr.filter(e=>e.best.includes('For a Party'));if(quick==='healthy')arr=arr.filter(e=>e.best.includes('Healthy'));if(quick==='treat')arr=arr.filter(e=>e.best.includes('Treat Yourself'));if(quick==='top')arr=arr.filter(e=>e.rating>=8);arr=arr.filter(e=>e.rating>=minRating&&(panelType==='all'||e.type===panelType)&&matchesAdvanced(e));$('#feed').innerHTML=arr.length?arr.map(e=>card(e)).join(''):'<p>Nothing matches those filters yet.</p>';bind()}
function renderMy(){let q=$('#search').value.toLowerCase(),t=$('#typeFilter').value,s=$('#sort').value,arr=data.filter(e=>e.mine&&(t==='all'||e.type===t)&&e.name.toLowerCase().includes(q));if(s==='rating')arr.sort((a,b)=>b.rating-a.rating);if(s==='name')arr.sort((a,b)=>a.name.localeCompare(b.name));if(s==='recent')arr.sort((a,b)=>new Date(b.date)-new Date(a.date));$('#myGrid').innerHTML=arr.map(e=>card(e,true)).join('');let mine=data.filter(e=>e.mine);$('#madeStat').textContent=mine.length;$('#avgStat').textContent=(mine.reduce((a,e)=>a+e.rating,0)/mine.length).toFixed(1);$('#againStat').textContent=Math.round(mine.filter(e=>e.rating>=5).length/mine.length*100)+'%';bind()}
function renderSaved(){$('#savedGrid').innerHTML=data.filter(e=>e.saved).map(e=>card(e,true)).join('');bind()}
function openDetail(id){let e=data.find(x=>x.id===id),verb=e.type==='food'?'made':'mixed';$('#detailBody').innerHTML=`<div class="detailhero"><img src="${e.img}" alt="${e.name}"><span class="badge detailbadge">${e.type==='food'?'Food':'Cocktail'}</span><div class="overlay"><h2>${e.name}</h2><p><strong>${e.author} ${verb} this</strong> · ${fmt(e.date)}</p></div></div><div class="detailcontent"><div class="pills">${[...e.tags,...e.best].map(t=>`<span class="pill">${t}</span>`).join('')}</div><div class="sourcebox"><div><span>Source</span><strong>${e.source||'Original recipe'}</strong></div>${e.url?`<a href="${e.url}" target="_blank" rel="noopener">Open original recipe ↗</a>`:'<span>No external link</span>'}</div><div class="ratingreview"><div class="ratinglockup"><div class="bigscore">${e.rating.toFixed(1)}<small>/10</small></div><p class="eyebrow">${meaning(e.rating).toUpperCase()}</p></div><div><h3>Why this rating</h3><p>${e.review}</p></div></div><div class="detailgrid"><div><div class="detailsection"><h3>Ingredients</h3><ul>${e.ingredients.map(i=>`<li>${i}</li>`).join('')}</ul></div><div class="detailsection"><h3>Directions</h3><ol>${e.directions.map(i=>`<li>${i}</li>`).join('')}</ol></div></div><div><div class="detailsection"><h3>What changed</h3><p>${e.changes}</p></div><div class="detailsection"><h3>Next time</h3><p>${e.next}</p></div></div></div><section class="made-again"><div class="made-again-head"><div><p class="eyebrow">MADE IT AGAIN</p><h3>${e.history.length} ${e.history.length===1?'cook':'cooks'} logged</h3></div><button class="primary">+ Log another</button></div><div class="history-list">${e.history.map(h=>`<div class="history-item"><span>${h.date}</span><b>${h.rating.toFixed(1)}</b><span>${h.note}</span></div>`).join('')}</div></section></div>`;$('#detail').showModal()}
$$('.nav').forEach(n=>n.onclick=()=>{$$('.nav').forEach(x=>x.classList.remove('active'));n.classList.add('active');$$('.view').forEach(v=>v.classList.remove('active'));$('#'+n.dataset.view).classList.add('active');const mobileNav=$('#mobileNav');if(mobileNav)mobileNav.value=n.dataset.view;if(n.dataset.view==='cookbook')renderMy();if(n.dataset.view==='saved')renderSaved()});$('[data-view-link]').onclick=e=>{e.preventDefault();$('.nav[data-view="home"]').click()};$$('.chip').forEach(c=>c.onclick=()=>{quick=c.dataset.filter;$$('.chip').forEach(x=>x.classList.remove('active'));c.classList.add('active');renderFeed()});$('#scoreToggle').onclick=()=>{let g=$('#scoreGuide');g.classList.toggle('hidden');$('#scoreToggle').textContent=g.classList.contains('hidden')?'See the full scoring guide':'Hide the full scoring guide'};$('#filterBtn').onclick=()=>{$('#filters').classList.add('open');$('#scrim').classList.add('open')};function closePanel(){$('#filters').classList.remove('open');$('#scrim').classList.remove('open')}$('#scrim').onclick=closePanel;$('[data-close="panel"]').onclick=closePanel;$('#range').oninput=e=>$('#rangeOut').textContent=Number(e.target.value).toFixed(1);$$('.segbtn').forEach(b=>b.onclick=()=>{panelType=b.dataset.type;$$('.segbtn').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('.food-filter-group').style.display=panelType==='cocktail'?'none':'block';$('.cocktail-filter-group').style.display=panelType==='food'?'none':'block'});$('#apply').onclick=()=>{minRating=Number($('#range').value);advanced={};$$('[data-filter-field]').forEach(s=>advanced[s.dataset.filterField]=s.value);closePanel();renderFeed()};$('#search').oninput=renderMy;$('#typeFilter').onchange=renderMy;$('#sort').onchange=renderMy;$('.dialog-close').onclick=()=>$('#detail').close();$('#addBtn').onclick=()=>{$('#date').value=new Date().toISOString().slice(0,10);$('#create').showModal()};$('.create-close').onclick=()=>$('#create').close();$$('.entry').forEach(e=>e.onclick=()=>{$$('.entry').forEach(x=>x.classList.remove('active'));e.classList.add('active');$('#foodFields').classList.toggle('hidden',e.dataset.entry!=='food');$('#cocktailFields').classList.toggle('hidden',e.dataset.entry!=='cocktail')});$$('.tagpick button').forEach(b=>b.onclick=()=>b.classList.toggle('selected'));$('#ratingInput').oninput=e=>{let r=Number(e.target.value);$('#meaning').textContent=meaning(r);$('#againPill').textContent=r>=5?'✓ Fine to have again':'Wouldn’t make again'};$$('input[type="file"][data-preview]').forEach(input=>input.onchange=e=>{let target=$('#'+input.dataset.preview);target.innerHTML='';[...e.target.files].forEach(file=>{let reader=new FileReader();reader.onload=ev=>{let img=document.createElement('img');img.src=ev.target.result;target.appendChild(img)};reader.readAsDataURL(file)})});$('#form').onsubmit=e=>{e.preventDefault();alert('Saved to My Cookbook — prototype mode');$('#create').close()};
const mobileNav = document.querySelector('#mobileNav');
if (mobileNav) {
  mobileNav.addEventListener('change', () => {
    const target = document.querySelector(`.nav[data-view="${mobileNav.value}"]`);
    if (target) target.click();
  });
}

renderFeed();renderMy();renderSaved();
